version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: skateshare@gmail.com
      PGADMIN_DEFAULT_PASSWORD: s1012564
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis:latest
    volumes:
      - ./config:/data
    command: "redis-server --requirepass sbrts"
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always


volumes:
  postgres-db-volume:
  pgadmin-data:

networks:
  default:
    name: airflow_net
